spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog-master.xml

server:
  port: ${port:8080}
